function TM4C1294NPDTPreDownload( ~, build_path , modelName)
    realtime.internal.runTM4C1294NPDTCmd('download', modelName, ...
                                        fullfile(build_path,'MW'));
end

%{
function TM4C1294NPDT_com_download( h, ~ , modelName)
cmd= sprintf( '%s%s%s', h.ToolsInfo.DownloadUtility,  ...
    h.ToolsInfo.DownloadUtilityFlags,  ...
    modelName) ;

%cmd= strrep( cmd, [ 'flash:w:', modelName] , [ 'lock:r:"', modelName, '.bin:r"'] ) ;

if system( cmd)
    eol= char( 10) ;
    errMsg= [ 'Could not connect to specified Stellaris board. ', eol, eol ...
        , 'Verify that your board is connected to your host, and that the ' ...
        , 'host COM port number and baud rate set in the model match the ' ...
        , 'port settings in Windows. ', eol, eol ...
        , 'To change the host COM port settings in your model, click ''Tools'', ' ...
        , 'click ''Run on Target Hardware'', and click ''Options...'' In the ' ...
        , 'Configuration Parameters dialog that opens, set the host COM ' ...
        , 'port parameters. ', eol, eol ...
        , 'To change the host COM port settings in Windows, open Device ' ...
        , 'Manager and open your board in COM ports group.'] ;
    error( message( 'realtime:setup:Error', errMsg) ) ;
end

end
%}
